apiVersion: v1
kind: Service
metadata:
  labels:
    service: udaconnect-api-location-svc-rest
  name: udaconnect-api-location-svc-rest
spec:
  ports:
  - name: "5001"
    port: 5001
    targetPort: 5000
    nodePort: 30003
  selector:
    service: udaconnect-api-location-svc-rest
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udaconnect-api-location-svc-rest
  name: udaconnect-api-location-svc-rest
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udaconnect-api-location-svc-rest
  template:
    metadata:
      labels:
        service: udaconnect-api-location-svc-rest
    spec:
      containers:
      - image: aalatishe86/location-rest:v1.0.0
        name: udaconnect-api-location-svc-rest
        imagePullPolicy: Always
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
        - name: KAFKA_TOPIC
          value: my-topic
        - name: KAFKA_PORT
          value: "9092"
        - name: KAFKA_HOST
          value: my-cluster-kafka-bootstrap.my-kafka-project.svc.cluster.local
      restartPolicy: Always
